FROM node:18-slim

# Instala Python
RUN apt-get update && apt-get install -y python3 python3-pip

# Carpeta base
WORKDIR /app

# Copiar todo el código fuente
COPY src/ ./src/

# Ir a la carpeta correcta
WORKDIR /app/src/paginaweb/Backend

# Instalar dependencias Python
RUN pip3 install --no-cache-dir -r requirements.txt

 WORKDIR /app/src/paginaweb
 RUN npm install

# Volver al backend para ejecutar
WORKDIR /app/src/paginaweb/Backend
CMD ["node", "server.js"]
